# Generated by Django 4.1 on 2022-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_commodity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(upload_to='data/uploads/images'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='specification',
            field=models.FileField(upload_to='data/uploads/specifications'),
        ),
    ]
